spring:
  application:
    name: ms-adapter

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""

  jpa:
    show-sql: true

logging:
  file:
    name: "app.log"

  level:
    root: ERROR
    org:
      springframework: ERROR
      hibernate: ERROR
      apache: ERROR
    az:
      company:
        msadapter: INFO
